if not vim.g.vscode then
    require("user.options")
    require("user.keymaps")
    require("user.plugins")
    require("user.colorscheme")
    require("user.cmp")
    require("user.lsp")
    require("user.telescope")
    require("user.treesitter")
    require("user.autopairs")
    require("user.comment")
    require("user.gitsigns")
    require("user.nvim-tree")
    require("user.bufferline")
    require("user.lualine")
    require("user.toggleterm")
    require("user.project")
    require("user.impatient")
    -- require("user.indentline")
    require("user.whichkey")
    require("user.autocommands")

    require("user.colorizer")
    -- require("user.vimwiki")
    require("user.telekasten")
    require("user.markdown-preview")
    require("user.dap")
    require("user.lsp-signature")
    require("user.illuminate")
    require("user.harpoon")
    require("user.matchup")
end
