-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "poimandres"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@HlargsNamedParams", { link = "Hlargs" })
hi(0, "@constant.builtin", { fg = "#add7ff" })
hi(0, "@constant.falsy", { fg = "#d0679d" })
hi(0, "@constructor", { fg = "#5de4c7" })
hi(0, "@function.builtin", { fg = "#add7ff" })
hi(0, "@function.call", { fg = "#a6accd" })
hi(0, "@import.identifier.tsx", { fg = "#add7ff" })
hi(0, "@import.identifier.typescript", { fg = "#add7ff" })
hi(0, "@keyword.export.tsx", { fg = "#5de4c7" })
hi(0, "@keyword.export.typescript", { fg = "#5de4c7" })
hi(0, "@keyword.function", { fg = "#add7ff" })
hi(0, "@keyword.import.tsx", { fg = "#5de4c7" })
hi(0, "@keyword.import.typescript", { fg = "#5de4c7" })
hi(0, "@keyword.operator", { fg = "#5de4c7" })
hi(0, "@keyword.return", { fg = "#5fb3a1" })
hi(0, "@label", { fg = "#91b4d5" })
hi(0, "@method", { fg = "#5de4c7" })
hi(0, "@parameter", { fg = "#e4f0fb" })
hi(0, "@property", { fg = "#add7ff" })
hi(0, "@punctuation.bracket", { fg = "#e4f0fb" })
hi(0, "@punctuation.delimiter", { fg = "#91b4d5" })
hi(0, "@punctuation.special", { fg = "#91b4d5" })
hi(0, "@string.escape", { fg = "#d0679d" })
hi(0, "@tag", { fg = "#5de4c7" })
hi(0, "@tag.attribute", { fg = "#91b4d5", italic = true })
hi(0, "@tag.delimiter", { fg = "#e4f0fb" })
hi(0, "@text", { fg = "#e4f0fb" })
hi(0, "@title", { bold = true, fg = "#5fb3a1" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@variable", { fg = "#e4f0fb" })
hi(0, "@variable.builtin", { fg = "#add7ff" })
hi(0, "ActionPreviewBorder", { link = "SagaBorder" })
hi(0, "ActionPreviewNormal", { link = "SagaNormal" })
hi(0, "ActionPreviewTitle", { bg = "#1b1e28", fg = "#767c9d" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#5de4c7" })
hi(0, "BufferCurrent", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "BufferCurrentIndex", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "BufferCurrentMod", { bg = "#1b1e28", fg = "#5de4c7" })
hi(0, "BufferCurrentSign", { bg = "#1b1e28", fg = "#a6accd" })
hi(0, "BufferCurrentTarget", { bg = "#1b1e28", fg = "#fffac2" })
hi(0, "BufferInactive", { fg = "#a6accd" })
hi(0, "BufferInactiveIndex", { fg = "#a6accd" })
hi(0, "BufferInactiveMod", { fg = "#5de4c7" })
hi(0, "BufferInactiveSign", { fg = "#767c9d" })
hi(0, "BufferInactiveTarget", { fg = "#fffac2" })
hi(0, "BufferTabpageFill", { bg = "#1b1e28", fg = "#1b1e28" })
hi(0, "BufferVisible", { fg = "#a6accd" })
hi(0, "BufferVisibleIndex", { fg = "#a6accd" })
hi(0, "BufferVisibleMod", { fg = "#5de4c7" })
hi(0, "BufferVisibleSign", { fg = "#767c9d" })
hi(0, "BufferVisibleTarget", { fg = "#fffac2" })
hi(0, "CallHierarchyBorder", { link = "SagaBorder" })
hi(0, "CallHierarchyIcon", { fg = "#fcc5e9" })
hi(0, "CallHierarchyNormal", { link = "SagaNormal" })
hi(0, "CallHierarchyTitle", { fg = "#fcc5e9" })
hi(0, "Character", { fg = "#d0679d" })
hi(0, "CmpItemAbbr", { fg = "#767c9d" })
hi(0, "CmpItemAbbrDefault", { fg = "#a6accd" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#d0679d", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#a6accd" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e4f0fb" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#a6accd" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#5de4c7" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#a6accd" })
hi(0, "CmpItemKind", { fg = "#91b4d5" })
hi(0, "CmpItemKindClass", { fg = "#fffac2" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#767c9d" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#89ddff" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#add7ff" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#d0679d" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#a6accd" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#5de4c7" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenuDefault", { fg = "#a6accd" })
hi(0, "CodeActionBorder", { link = "SagaBorder" })
hi(0, "CodeActionNormal", { link = "SagaNormal" })
hi(0, "CodeActionNumber", { fg = "#91b4d5" })
hi(0, "CodeActionText", { fg = "#fffac2" })
hi(0, "ColorColumn", { bg = "#a6accd" })
hi(0, "Comment", { fg = "#a6accd" })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#a6accd" })
hi(0, "Constant", { fg = "#e4f0fb" })
hi(0, "CurSearch", { bg = "#add7ff", fg = "#171922" })
hi(0, "Cursor", { bg = "#a6accd", fg = "#171922" })
hi(0, "CursorColumn", { bg = "#303340" })
hi(0, "CursorLine", { bg = "#303340" })
hi(0, "CursorLineNr", { fg = "#e4f0fb" })
hi(0, "DarkenedPanel", { bg = "#171922" })
hi(0, "DarkenedStatusline", { bg = "#171922" })
hi(0, "DefinitionBorder", { link = "SagaBorder" })
hi(0, "DefinitionNormal", { link = "SagaNormal" })
hi(0, "DefinitionSearch", { link = "Search" })
hi(0, "Delimiter", { fg = "#a6accd" })
hi(0, "DiagnosticBorder", { link = "SagaBorder" })
hi(0, "DiagnosticDefaultError", { fg = "#d0679d" })
hi(0, "DiagnosticDefaultHint", { fg = "#89ddff" })
hi(0, "DiagnosticDefaultInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticDefaultWarn", { fg = "#fffac2" })
hi(0, "DiagnosticError", { ctermfg = 1, fg = "#d0679d" })
hi(0, "DiagnosticErrorBorder", { link = "DiagnosticError" })
hi(0, "DiagnosticFloatingError", { fg = "#d0679d" })
hi(0, "DiagnosticFloatingHint", { fg = "#89ddff" })
hi(0, "DiagnosticFloatingInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticFloatingWarn", { fg = "#fffac2" })
hi(0, "DiagnosticHint", { ctermfg = 4, fg = "#89ddff" })
hi(0, "DiagnosticHintBorder", { link = "DiagnosticHint" })
hi(0, "DiagnosticInfo", { ctermfg = 6, fg = "#91b4d5" })
hi(0, "DiagnosticInfoBorder", { link = "DiagnosticInfo" })
hi(0, "DiagnosticNormal", { link = "SagaNormal" })
hi(0, "DiagnosticPos", { fg = "#767c9d" })
hi(0, "DiagnosticSignError", { fg = "#d0679d" })
hi(0, "DiagnosticSignHint", { fg = "#89ddff" })
hi(0, "DiagnosticSignInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticSignWarn", { fg = "#fffac2" })
hi(0, "DiagnosticSource", { fg = "#767c9d" })
hi(0, "DiagnosticStatusLineError", { bg = "#171922", fg = "#d0679d" })
hi(0, "DiagnosticStatusLineHint", { bg = "#171922", fg = "#89ddff" })
hi(0, "DiagnosticStatusLineInfo", { bg = "#171922", fg = "#91b4d5" })
hi(0, "DiagnosticStatusLineWarn", { bg = "#171922", fg = "#fffac2" })
hi(0, "DiagnosticUnderlineError", { sp = "#d0679d", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#89ddff", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#91b4d5", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#fffac2", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#d0679d" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#89ddff" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#91b4d5" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#fffac2" })
hi(0, "DiagnosticWarn", { ctermfg = 3, fg = "#fffac2" })
hi(0, "DiagnosticWarnBorder", { link = "DiagnosticWarn" })
hi(0, "DiagnosticWord", { fg = "#ffffff" })
hi(0, "DiffAdd", { bg = "#3c8178", ctermbg = 2, ctermfg = 15 })
hi(0, "DiffChange", { bg = "#a6accd" })
hi(0, "DiffDelete", { bg = "#764363", ctermfg = 1 })
hi(0, "DiffText", { bg = "#3d6965", ctermbg = 6, ctermfg = 15 })
hi(0, "DiffviewDiffAddAsDelete", { bg = "#764363" })
hi(0, "DiffviewDim1", { fg = "#a6accd" })
hi(0, "DiffviewFilePanelCounter", { bold = true, fg = "#a6accd" })
hi(0, "DiffviewFilePanelFileName", { fg = "#e4f0fb" })
hi(0, "DiffviewFilePanelTitle", { bold = true, fg = "#e4f0fb" })
hi(0, "DiffviewPrimary", { fg = "#add7ff" })
hi(0, "DiffviewSecondary", { fg = "#5de4c7" })
hi(0, "Directory", { ctermfg = 6, fg = "#91b4d5" })
hi(0, "Error", { ctermbg = 1, ctermfg = 15, fg = "#d0679d" })
hi(0, "ErrorMsg", { bold = true, ctermfg = 1, fg = "#d0679d" })
hi(0, "Exception", { fg = "#91b4d5" })
hi(0, "FinderBorder", { link = "SagaBorder" })
hi(0, "FinderCount", { link = "Label" })
hi(0, "FinderFileName", { fg = "#ffffff" })
hi(0, "FinderIcon", { fg = "#fffac2" })
hi(0, "FinderNormal", { link = "SagaNormal" })
hi(0, "FinderPreviewBorder", { link = "SagaBorder" })
hi(0, "FinderPreviewSearch", { link = "Search" })
hi(0, "FinderSelection", { fg = "#767c9d" })
hi(0, "FinderSpinner", { fg = "#d0679d" })
hi(0, "FinderSpinnerTitle", { fg = "#d0679d" })
hi(0, "FinderType", { fg = "#5de4c7" })
hi(0, "FinderVirtText", { fg = "#89ddff" })
hi(0, "Float", { fg = "#5de4c7" })
hi(0, "FloatBorder", { fg = "#171922" })
hi(0, "FloatTitle", { fg = "#767c9d" })
hi(0, "FoldColumn", { fg = "#767c9d" })
hi(0, "Folded", { bg = "#171922", fg = "#e4f0fb" })
hi(0, "Function", { ctermfg = 6, fg = "#add7ff" })
hi(0, "GitSignsAdd", { fg = "#5de4c7" })
hi(0, "GitSignsChange", { fg = "#add7ff" })
hi(0, "GitSignsDelete", { fg = "#d0679d" })
hi(0, "GitSignsStagedAdd", { fg = "#2e7263" })
hi(0, "GitSignsStagedAddCul", { fg = "#2e7263" })
hi(0, "GitSignsStagedAddLn", { bg = "#3c8178" })
hi(0, "GitSignsStagedAddNr", { fg = "#2e7263" })
hi(0, "GitSignsStagedChange", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangeCul", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangeLn", { bg = "#a6accd" })
hi(0, "GitSignsStagedChangeNr", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangedelete", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#566b7f" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#a6accd" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#566b7f" })
hi(0, "GitSignsStagedDelete", { fg = "#68334e" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#68334e" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#68334e" })
hi(0, "GitSignsStagedTopdelete", { fg = "#68334e" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#68334e" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#68334e" })
hi(0, "Hlargs", { fg = "#ef9062" })
hi(0, "HopCursor", { fg = "#91b4d5" })
hi(0, "HopNextKey", { fg = "#89ddff" })
hi(0, "HopNextKey1", { fg = "#5de4c7" })
hi(0, "HopNextKey2", { fg = "#5fb3a1" })
hi(0, "HopUnmatched", { fg = "#506477" })
hi(0, "HoverBorder", { link = "SagaBorder" })
hi(0, "HoverNormal", { link = "SagaNormal" })
hi(0, "Identifier", { ctermfg = 4, fg = "#a6accd" })
hi(0, "IlluminatedWordRead", { underline = true })
hi(0, "IlluminatedWordText", { underline = true })
hi(0, "IlluminatedWordWrite", { underline = true })
hi(0, "IncSearch", { bg = "#add7ff", fg = "#171922" })
hi(0, "Include", { fg = "#a6accd" })
hi(0, "IndentBlanklineChar", { fg = "#303340" })
hi(0, "IndentBlanklineContextChar", { fg = "#fffac2" })
hi(0, "IndentBlanklineContextStart", { fg = "#fffac2" })
hi(0, "IndentBlanklineSpaceChar", { link = "Whitespace" })
hi(0, "IndentBlanklineSpaceCharBlankline", { link = "Whitespace" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#91b4d5" })
hi(0, "Label", { fg = "#e4f0fb" })
hi(0, "LazyBold", { bold = true })
hi(0, "LazyItalic", { italic = true })
hi(0, "LeapBackground", { bg = "#303340" })
hi(0, "LeapLabelPrimary", { bg = "#5de4c7", fg = "#1b1e28" })
hi(0, "LeapLabelSecondary", { bg = "#89ddff", fg = "#1b1e28" })
hi(0, "LeapLabelSelected", { bg = "#fffac2", fg = "#1b1e28" })
hi(0, "LeapMatch", { bg = "#fcc5e9", fg = "#1b1e28" })
hi(0, "LineNr", { fg = "#506477" })
hi(0, "LspCodeLens", { fg = "#a6accd" })
hi(0, "LspCodeLensSeparator", { fg = "#506477" })
hi(0, "LspReferenceRead", { bg = "#add7ff" })
hi(0, "LspReferenceText", { bg = "#add7ff" })
hi(0, "LspReferenceWrite", { bg = "#add7ff" })
hi(0, "LspSagaLightBulb", { link = "DiagnosticSignHint" })
hi(0, "LspSignatureActiveParameter", { bg = "#a6accd" })
hi(0, "MatchParen", { bg = "#506477", fg = "#171922" })
hi(0, "ModeMsg", { ctermfg = 2, fg = "#91b4d5" })
hi(0, "ModesCopy", { bg = "#fffac2" })
hi(0, "ModesDelete", { bg = "#d0679d" })
hi(0, "ModesInsert", { bg = "#5de4c7" })
hi(0, "ModesVisual", { bg = "#fffac2" })
hi(0, "MoreMsg", { ctermfg = 6, fg = "#91b4d5" })
hi(0, "NonText", { fg = "#7390aa" })
hi(0, "Normal", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "NormalFloat", { bg = "#171922", fg = "#e4f0fb" })
hi(0, "NormalNC", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "NotifyDEBUGBorder", { fg = "#89ddff" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#d0679d" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#5de4c7" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#89ddff" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#fffac2" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "Number", { fg = "#5de4c7" })
hi(0, "NvimInternalError", { bg = "#d0679d", ctermbg = 9, ctermfg = 9, fg = "#ffffff" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#506477" })
hi(0, "NvimTreeFileDeleted", { fg = "#d0679d" })
hi(0, "NvimTreeFileDirty", { fg = "#7390aa" })
hi(0, "NvimTreeFileMerge", { fg = "#add7ff" })
hi(0, "NvimTreeFileNew", { fg = "#5de4c7" })
hi(0, "NvimTreeFileRenamed", { fg = "#506477" })
hi(0, "NvimTreeFileStaged", { fg = "#89ddff" })
hi(0, "NvimTreeFolderIcon", { fg = "#91b4d5" })
hi(0, "NvimTreeFolderName", { fg = "#91b4d5" })
hi(0, "NvimTreeGitDeleted", { fg = "#d0679d" })
hi(0, "NvimTreeGitDirty", { fg = "#7390aa" })
hi(0, "NvimTreeGitMerge", { fg = "#add7ff" })
hi(0, "NvimTreeGitNew", { fg = "#5de4c7" })
hi(0, "NvimTreeGitRenamed", { fg = "#42675a" })
hi(0, "NvimTreeGitStaged", { fg = "#89ddff" })
hi(0, "NvimTreeImageFile", { fg = "#e4f0fb" })
hi(0, "NvimTreeNormal", { fg = "#e4f0fb" })
hi(0, "NvimTreeOpenedFile", { bg = "#303340", fg = "#e4f0fb" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeRootFolder", { fg = "#5de4c7" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeWindowPicker", { bg = "#a6accd" })
hi(0, "Operator", { fg = "#add7ff" })
hi(0, "OutlineIndent", { fg = "#add7ff" })
hi(0, "OutlinePreviewBorder", { link = "SagaNormal" })
hi(0, "OutlinePreviewNormal", { link = "SagaBorder" })
hi(0, "Pmenu", { bg = "#171922", fg = "#a6accd" })
hi(0, "PmenuSbar", { bg = "#767c9d" })
hi(0, "PmenuSel", { bg = "#303340", blend = 0, fg = "#e4f0fb" })
hi(0, "PmenuThumb", { bg = "#506477" })
hi(0, "PounceAccept", { bg = "#e4f0fb", fg = "#d0679d" })
hi(0, "PounceAcceptBest", { bg = "#e4f0fb", fg = "#e4f0fb" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreProc", { fg = "#e4f0fb" })
hi(0, "Question", { ctermfg = 6, fg = "#fffac2" })
hi(0, "RedrawDebugClear", { bg = "#fffac2", ctermbg = 3, ctermfg = 15, fg = "#ffffff" })
hi(0, "RedrawDebugComposed", { bg = "#5fb3a1", ctermbg = 2, ctermfg = 15, fg = "#ffffff" })
hi(0, "RedrawDebugRecompose", { bg = "#d0679d", ctermbg = 1, ctermfg = 15, fg = "#ffffff" })
hi(0, "RenameBorder", { link = "SagaBorder" })
hi(0, "RenameMatch", { link = "Search" })
hi(0, "RenameNormal", { fg = "#ffffff" })
hi(0, "Repeat", { fg = "#91b4d5" })
hi(0, "SagaBeacon", { bg = "#fffac2" })
hi(0, "SagaBorder", { bg = "#1b1e28", fg = "#767c9d" })
hi(0, "SagaCollapse", { fg = "#5fb3a1" })
hi(0, "SagaExpand", { fg = "#5fb3a1" })
hi(0, "SagaNormal", { bg = "#1b1e28" })
hi(0, "SagaShadow", { bg = "#171922" })
hi(0, "ScrollViewHighlight0", { bg = "#1b1e28", fg = "#e4f0fb" })
hi(0, "Search", { bg = "#506477", ctermbg = 3, ctermfg = 15, fg = "#ffffff" })
hi(0, "SignAdd", { link = "GitSignsAdd" })
hi(0, "SignChange", { link = "GitSignsChange" })
hi(0, "SignColumn", { fg = "#e4f0fb" })
hi(0, "SignDelete", { link = "GitSignsDelete" })
hi(0, "Special", { ctermfg = 6, fg = "#767c9d" })
hi(0, "SpecialComment", { fg = "#a6accd" })
hi(0, "SpecialKey", { fg = "#5de4c7" })
hi(0, "SpellBad", { sp = "#d0679d", undercurl = true })
hi(0, "SpellCap", { sp = "#89ddff", undercurl = true })
hi(0, "SpellLocal", { sp = "#fffac2", undercurl = true })
hi(0, "SpellRare", { sp = "#89ddff", undercurl = true })
hi(0, "Statement", { fg = "#e4f0fb" })
hi(0, "StatusLine", { bg = "#171922", fg = "#91b4d5" })
hi(0, "StatusLineNC", { bg = "#1b1e28", fg = "#91b4d5" })
hi(0, "StatusLineTerm", { link = "StatusLine" })
hi(0, "StatusLineTermNC", { link = "StatusLineNC" })
hi(0, "Stl91b4d5_171922__", { bg = "#171922", fg = "#91b4d5" })
hi(0, "String", { ctermfg = 2, fg = "#5de4c7" })
hi(0, "TSInclude", { fg = "#add7ff" })
hi(0, "TSURI", { fg = "#91b4d5" })
hi(0, "TabLine", { bg = "#171922", fg = "#91b4d5" })
hi(0, "TabLineFill", { bg = "#171922" })
hi(0, "TabLineSel", { bg = "#303340", fg = "#e4f0fb" })
hi(0, "Tag", { fg = "#e4f0fb" })
hi(0, "TelescopeBorder", { fg = "#303340" })
hi(0, "TelescopeMatching", { fg = "#5de4c7" })
hi(0, "TelescopeNormal", { fg = "#e4f0fb" })
hi(0, "TelescopePreviewTitle", { bg = "#5de4c7", fg = "#1b1e28" })
hi(0, "TelescopePromptBorder", { fg = "#303340" })
hi(0, "TelescopePromptNormal", { fg = "#e4f0fb" })
hi(0, "TelescopePromptPrefix", { fg = "#767c9d" })
hi(0, "TelescopePromptTitle", { bg = "#89ddff", fg = "#1b1e28" })
hi(0, "TelescopeResultsDiffAdd", { fg = "#5de4c7" })
hi(0, "TelescopeResultsDiffChange", { fg = "#fffac2" })
hi(0, "TelescopeResultsDiffDelete", { fg = "#d0679d" })
hi(0, "TelescopeSelection", { bg = "#303340", fg = "#e4f0fb" })
hi(0, "TelescopeTitle", { fg = "#767c9d" })
hi(0, "TerminalBorder", { link = "SagaBorder" })
hi(0, "TerminalNormal", { link = "SagaNormal" })
hi(0, "Title", { fg = "#e4f0fb" })
hi(0, "TitleIcon", { fg = "#add7ff" })
hi(0, "TitleString", { fg = "#add7ff" })
hi(0, "Todo", { bg = "#fffac2", fg = "#171922" })
hi(0, "Type", { fg = "#a6accd" })
hi(0, "VertSplit", { fg = "#171922" })
hi(0, "Visual", { bg = "#506477", ctermbg = 0, ctermfg = 15, fg = "#e4f0fb" })
hi(0, "WarningMsg", { ctermfg = 3, fg = "#fffac2" })
hi(0, "WhichKey", { fg = "#e4f0fb" })
hi(0, "WhichKeyDesc", { fg = "#e4f0fb" })
hi(0, "WhichKeyFloat", { bg = "#171922" })
hi(0, "WhichKeyGroup", { fg = "#e4f0fb" })
hi(0, "WhichKeySeparator", { fg = "#e4f0fb" })
hi(0, "WhichKeyValue", { fg = "#e4f0fb" })
hi(0, "Whitespace", { fg = "#506477" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "cssClassName", { fg = "#5fb3a1", italic = true })
hi(0, "cssDefinition", { fg = "#add7ff" })
hi(0, "cssPseudoClass", { fg = "#91b4d5", italic = true })
hi(0, "cssTSError", { link = "cssClassName" })
hi(0, "cssTSFunction", { fg = "#a6accd" })
hi(0, "cssTSKeyword", { fg = "#a6accd" })
hi(0, "cssTSProperty", { fg = "#add7ff" })
hi(0, "cssTSType", { fg = "#5de4c7" })
hi(0, "debugBreakpoint", { bg = "#1b1e28", fg = "#d0679d" })
hi(0, "debugPC", { bg = "#303340" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "field", { fg = "#e4f0fb" })
hi(0, "htmlH1", { bold = true, fg = "#5de4c7" })
hi(0, "htmlH2", { bold = true, fg = "#5de4c7" })
hi(0, "lCursor", { bg = "#e4f0fb", fg = "#1b1e28" })
hi(0, "luaTSConstructor", { fg = "#a6accd" })
hi(0, "markdownCode", { fg = "#a6accd" })
hi(0, "markdownCodeBlock", { fg = "#5fb3a1" })
hi(0, "markdownH1", { bold = true, fg = "#add7ff" })
hi(0, "markdownH2", { bold = true, fg = "#add7ff" })
hi(0, "markdownH3", { bold = true, fg = "#add7ff" })
hi(0, "markdownH4", { bold = true, fg = "#add7ff" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#7390aa" })
hi(0, "markdownLinkText", { fg = "#89ddff", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#171922", fg = "#e4f0fb" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#5fb3a1" })
hi(0, "mkdCodeStart", { bold = true, fg = "#5fb3a1" })
hi(0, "mkdLink", { fg = "#89ddff", underline = true })
hi(0, "qfFileName", { fg = "#767c9d" })
hi(0, "qfLineNr", { fg = "#506477" })
hi(0, "rainbowcol1", { fg = "#89ddff" })
hi(0, "rainbowcol2", { fg = "#5de4c7" })
hi(0, "rainbowcol3", { fg = "#fffac2" })
hi(0, "rainbowcol4", { fg = "#add7ff" })
hi(0, "rainbowcol5", { fg = "#5fb3a1" })
hi(0, "rainbowcol6", { fg = "#d0679d" })
hi(0, "rainbowcol7", { fg = "#91b4d5" })
hi(0, "typescriptBlock", { fg = "#e4f0fb" })
hi(0, "typescriptCastKeyword", { fg = "#767c9d" })
hi(0, "typescriptConstraint", { fg = "#5de4c7" })
hi(0, "typescriptDefault", { fg = "#5de4c7" })
hi(0, "typescriptEnum", { fg = "#7390aa" })
hi(0, "typescriptExport", { fg = "#5de4c7" })
hi(0, "typescriptIdentifierName", { fg = "#767c9d" })
hi(0, "typescriptObjectType", { fg = "#a6accd" })
hi(0, "typescriptParenExp", { fg = "#767c9d" })
hi(0, "typescriptTSInclude", { fg = "#5de4c7" })
hi(0, "typescriptTypeCast", { fg = "#767c9d" })
hi(0, "typescriptVariable", { fg = "#add7ff" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#171922"
g.terminal_color_1 = "#d0679d"
g.terminal_color_2 = "#5de4c7"
g.terminal_color_3 = "#fffac2"
g.terminal_color_4 = "#89ddff"
g.terminal_color_5 = "#fcc5e9"
g.terminal_color_6 = "#89ddff"
g.terminal_color_7 = "#ffffff"
g.terminal_color_8 = "#171922"
g.terminal_color_9 = "#d0679d"
g.terminal_color_10 = "#5de4c7"
g.terminal_color_11 = "#fffac2"
g.terminal_color_12 = "#add7ff"
g.terminal_color_13 = "#fcc5e9"
g.terminal_color_14 = "#add7ff"
g.terminal_color_15 = "#ffffff"
