-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "tokyonight-night"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@HlargsNamedParams", { link = "Hlargs" })
hi(0, "@HlargsNamedParams.python", { fg = "#50587f" })
hi(0, "@annotation", { link = "PreProc" })
hi(0, "@attribute", { link = "PreProc" })
hi(0, "@character.printf", { link = "SpecialChar" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { fg = "#5b638b" })
hi(0, "@comment.error", { fg = "#c84647" })
hi(0, "@comment.hint", { fg = "#1aac90" })
hi(0, "@comment.info", { fg = "#0ea9c5" })
hi(0, "@comment.note", { fg = "#1aac90" })
hi(0, "@comment.todo", { fg = "#7095e2" })
hi(0, "@comment.warning", { fg = "#cca061" })
hi(0, "@constant.builtin", { fg = "#e8915e" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@constructor", { link = "Type" })
hi(0, "@constructor.tsx", { fg = "#28b2cc" })
hi(0, "@controlFlow", { link = "Conditional" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@exception", { link = "Conditional" })
hi(0, "@formatSpecifier", { link = "@punctuation.bracket" })
hi(0, "@function.builtin", { bold = true, fg = "#7c9de5" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "@function.method" })
hi(0, "@keyword", { fg = "#9072c6" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { link = "@keyword" })
hi(0, "@keyword.import", { link = "@keyword" })
hi(0, "@keyword.operator", { link = "@operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "Conditional" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { link = "@variable.member" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
hi(0, "@lsp.type.generic", { link = "@variable" })
hi(0, "@lsp.type.interface", { fg = "#56b9d8" })
hi(0, "@lsp.type.interface.typescript", { link = "Type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#c84647", undercurl = true })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#2594ab" })
hi(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#2594ab" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "@constant" })
hi(0, "@markup", { link = "@none" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#7aa2f7" })
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#e0af68" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#9ece6a" })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#1abc9c" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#bb9af7" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#9d7cd8" })
hi(0, "@markup.link", { fg = "#1aac90" })
hi(0, "@markup.link.label", { link = "@markup.link.url" })
hi(0, "@markup.link.label.symbol", { link = "Identifier" })
hi(0, "@markup.link.url", { link = "Underlined" })
hi(0, "@markup.list", { fg = "#7ecae9" })
hi(0, "@markup.list.checked", { fg = "#6ac7ba" })
hi(0, "@markup.list.markdown", { link = "@punctuation.bracket" })
hi(0, "@markup.list.unchecked", { fg = "#7095e2" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.raw.block.markdown", {})
hi(0, "@markup.raw.markdown_inline", { bg = "#3d4461", fg = "#7095e2" })
hi(0, "@module", { link = "Include" })
hi(0, "@module.builtin", { fg = "#e16d84" })
hi(0, "@namespace.builtin", { link = "@variable.builtin" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#afb9e0" })
hi(0, "@property", { link = "@variable.member" })
hi(0, "@punctuation.bracket", { fg = "#5b638b" })
hi(0, "@punctuation.delimiter", { fg = "#666f97" })
hi(0, "@punctuation.special", { link = "@punctuation.bracket" })
hi(0, "@string.documentation", { fg = "#5b638b" })
hi(0, "@string.escape", { fg = "#ab8de2" })
hi(0, "@string.regexp", { link = "Constant" })
hi(0, "@tag", { link = "Label" })
hi(0, "@tag.attribute", { link = "@property" })
hi(0, "@tag.delimiter", { link = "@punctuation.bracket" })
hi(0, "@tag.delimiter.tsx", { fg = "#5670aa" })
hi(0, "@tag.javascript", { fg = "#e16d84" })
hi(0, "@tag.tsx", { fg = "#e16d84" })
hi(0, "@type.builtin", { fg = "#3d98a7" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "@keyword" })
hi(0, "@variable", { fg = "#afb9e0" })
hi(0, "@variable.builtin", { fg = "#e16d84", italic = true })
hi(0, "@variable.member", { fg = "#0ea9c5" })
hi(0, "@variable.parameter", { italic = true })
hi(0, "@variable.parameter.builtin", { fg = "#caa87f" })
hi(0, "Bold", { bold = true, fg = "#afb9e0" })
hi(0, "Character", { fg = "#91bc63" })
hi(0, "CmpDocumentation", { bg = "#16161e", fg = "#afb9e0" })
hi(0, "CmpDocumentationBorder", { bg = "#16161e", fg = "#2694aa" })
hi(0, "CmpGhostText", { fg = "#3d4461" })
hi(0, "CmpItemAbbr", { fg = "#afb9e0" })
hi(0, "CmpItemAbbrDefault", { fg = "#afb9e0" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#383e5b", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#50587f" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#7095e2" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#afb9e0" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#afb9e0" })
hi(0, "CmpItemKindArray", { link = "LspKindArray" })
hi(0, "CmpItemKindBoolean", { link = "LspKindBoolean" })
hi(0, "CmpItemKindClass", { link = "LspKindClass" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCodeium", { fg = "#1aac90" })
hi(0, "CmpItemKindColor", { link = "LspKindColor" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "LspKindConstant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "LspKindConstructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#1aac90" })
hi(0, "CmpItemKindDefault", { fg = "#28b2cc" })
hi(0, "CmpItemKindEnum", { link = "LspKindEnum" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "LspKindEvent" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "LspKindField" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "LspKindFile" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "LspKindFolder" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "LspKindFunction" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "LspKindInterface" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKey", { link = "LspKindKey" })
hi(0, "CmpItemKindKeyword", { link = "LspKindKeyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "LspKindMethod" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "LspKindModule" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindNamespace", { link = "LspKindNamespace" })
hi(0, "CmpItemKindNull", { link = "LspKindNull" })
hi(0, "CmpItemKindNumber", { link = "LspKindNumber" })
hi(0, "CmpItemKindObject", { link = "LspKindObject" })
hi(0, "CmpItemKindOperator", { link = "LspKindOperator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPackage", { link = "LspKindPackage" })
hi(0, "CmpItemKindProperty", { link = "LspKindProperty" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "LspKindReference" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "LspKindSnippet" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindString", { link = "LspKindString" })
hi(0, "CmpItemKindStruct", { link = "LspKindStruct" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSupermaven", { fg = "#1aac90" })
hi(0, "CmpItemKindTabNine", { fg = "#1aac90" })
hi(0, "CmpItemKindText", { link = "LspKindText" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "LspKindUnit" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "LspKindValue" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "LspKindVariable" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#50587f" })
hi(0, "CmpItemMenuDefault", { fg = "#afb9e0" })
hi(0, "ColorColumn", { bg = "#181922" })
hi(0, "Comment", { fg = "#50587f" })
hi(0, "Conceal", { fg = "#6a7196" })
hi(0, "Conditional", { fg = "#9072c6", italic = true })
hi(0, "Constant", { fg = "#e8915e" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#afb9e0", fg = "#1a1b26" })
hi(0, "CursorColumn", { bg = "#222534" })
hi(0, "CursorIM", { bg = "#afb9e0", fg = "#1a1b26" })
hi(0, "CursorLine", { bg = "#222534" })
hi(0, "CursorLineCurrent", { bg = "#292e42" })
hi(0, "CursorLineNr", { bg = "#181922", fg = "#6a7196" })
hi(0, "DapStoppedLine", { bg = "#2c282c" })
hi(0, "DapUIDecoration", { fg = "#383e5b" })
hi(0, "DapUIModifiedValue", { link = "@variable" })
hi(0, "DapUIScope", { bold = true, fg = "#afb9e0" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIValue", { link = "@HlargsNamedParams" })
hi(0, "DapUIWatchesEmpty", { link = "DapUIWatchesError" })
hi(0, "DapUIWatchesError", { fg = "#c84647" })
hi(0, "DapUIWatchesValue", { fg = "#383e5b" })
hi(0, "Debug", { fg = "#e8915e" })
hi(0, "Delimiter", { link = "Special" })
hi(0, "DiagnosticError", { fg = "#c84647" })
hi(0, "DiagnosticHint", { fg = "#1aac90" })
hi(0, "DiagnosticInfo", { fg = "#0ea9c5" })
hi(0, "DiagnosticSignError", { bg = "#181922", fg = "#c84647" })
hi(0, "DiagnosticSignHint", { bg = "#181922", fg = "#1aac90" })
hi(0, "DiagnosticSignInfo", { bg = "#181922", fg = "#0ea9c5" })
hi(0, "DiagnosticSignWarn", { bg = "#181922", fg = "#cca061" })
hi(0, "DiagnosticUnderlineError", { sp = "#c84647", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#1aac90", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#0ea9c5", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#cca061", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#3d4461" })
hi(0, "DiagnosticVirtualTextError", { bg = "#2b1f29", fg = "#c84647" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#1a2a31", fg = "#1aac90" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#192936", fg = "#0ea9c5" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#2c282c", fg = "#cca061" })
hi(0, "DiagnosticWarn", { fg = "#cca061" })
hi(0, "DiffAdd", { bg = "#20303b" })
hi(0, "DiffChange", { bg = "#1f2231" })
hi(0, "DiffDelete", { bg = "#37222c" })
hi(0, "DiffText", { bg = "#394b70" })
hi(0, "DiffviewDiffAddAsDelete", { bg = "#37222c" })
hi(0, "DiffviewDim1", { fg = "#50587f" })
hi(0, "DiffviewFilePanelCounter", { bold = true, fg = "#9072c6" })
hi(0, "DiffviewFilePanelFileName", { fg = "#afb9e0" })
hi(0, "DiffviewFilePanelTitle", { bold = true, fg = "#ab8de2" })
hi(0, "DiffviewPrimary", { fg = "#7095e2" })
hi(0, "DiffviewSecondary", { fg = "#1aac90" })
hi(0, "Directory", { fg = "#7095e2" })
hi(0, "EndOfBuffer", { fg = "#1a1b26" })
hi(0, "Error", { fg = "#c84647" })
hi(0, "ErrorMsg", { fg = "#c84647" })
hi(0, "FlashBackdrop", { fg = "#4e5675" })
hi(0, "FlashLabel", { bg = "#e80373", fg = "#1a1b26" })
hi(0, "FloatBorder", { bg = "#16161e", fg = "#2694aa" })
hi(0, "FloatTitle", { bg = "#16161e", fg = "#2694aa" })
hi(0, "FoldColumn", { bg = "#1a1b26", fg = "#50587f" })
hi(0, "Folded", { bg = "#383e5b", fg = "#7095e2" })
hi(0, "Foo", { bg = "#e80373", fg = "#afb9e0" })
hi(0, "Function", { bold = true, fg = "#7095e2" })
hi(0, "GitSignsAdd", { fg = "#40909e" })
hi(0, "GitSignsAddNr", { bg = "#181922", bold = true, fg = "#40909e" })
hi(0, "GitSignsChange", { fg = "#5a79ac" })
hi(0, "GitSignsChangeNr", { bg = "#181922", bold = true, fg = "#5a79ac" })
hi(0, "GitSignsDelete", { fg = "#85474f" })
hi(0, "GitSignsDeleteNr", { bg = "#181922", bold = true, fg = "#85474f" })
hi(0, "GitSignsStagedAdd", { fg = "#20484f" })
hi(0, "GitSignsStagedAddCul", { fg = "#20484f" })
hi(0, "GitSignsStagedAddLn", { bg = "#20303b" })
hi(0, "GitSignsStagedAddNr", { bg = "#181922", fg = "#20484f" })
hi(0, "GitSignsStagedChange", { fg = "#2d3c56" })
hi(0, "GitSignsStagedChangeCul", { fg = "#2d3c56" })
hi(0, "GitSignsStagedChangeLn", { bg = "#1f2231" })
hi(0, "GitSignsStagedChangeNr", { bg = "#181922", fg = "#2d3c56" })
hi(0, "GitSignsStagedChangedelete", { fg = "#2d3c56" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#2d3c56" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#1f2231" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#181922", fg = "#2d3c56" })
hi(0, "GitSignsStagedDelete", { fg = "#422327" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#422327" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#181922", fg = "#422327" })
hi(0, "GitSignsStagedTopdelete", { fg = "#422327" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#422327" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#181922", fg = "#422327" })
hi(0, "HarpoonBorder", { link = "NormalFloat" })
hi(0, "HarpoonTitle", { link = "TelescopePromptTitle" })
hi(0, "HarpoonWindow", { link = "NormalFloat" })
hi(0, "HeirlineCwd", { bg = "#222534", bold = true, fg = "#7095e2" })
hi(0, "HeirlineEnd", { bg = "#181922", fg = "#222534" })
hi(0, "HeirlineErrorCount", { bg = "#c84647", fg = "#181922" })
hi(0, "HeirlineErrorWarn", { bg = "#c84647", fg = "#cca061" })
hi(0, "HeirlineFileName", { bg = "#222534", bold = true, italic = true })
hi(0, "HeirlineFileStatus", { bg = "#222534" })
hi(0, "HeirlineFileType", { bg = "#222534" })
hi(0, "HeirlineGitBranch", { bg = "#9072c6", fg = "#181922" })
hi(0, "HeirlineGitLeft", { bg = "#9072c6", fg = "#222534" })
hi(0, "HeirlineGitRight", { bg = "#222534", fg = "#9072c6" })
hi(0, "HeirlineHintCount", { bg = "#1aac90", fg = "#181922" })
hi(0, "HeirlineHintFiletype", { bg = "#1aac90", fg = "#222534" })
hi(0, "HeirlineInfoCount", { bg = "#0ea9c5", fg = "#181922" })
hi(0, "HeirlineInfoHint", { bg = "#0ea9c5", fg = "#1aac90" })
hi(0, "HeirlineLspClients", { bg = "#222534", bold = true, italic = true })
hi(0, "HeirlineNoneError", { bg = "#181922", fg = "#c84647" })
hi(0, "HeirlineSeparator", { bg = "#222534", fg = "#5b638b" })
hi(0, "HeirlineToolsError", { bg = "#222534", fg = "#c84647" })
hi(0, "HeirlineWarnCount", { bg = "#cca061", fg = "#181922" })
hi(0, "HeirlineWarnInfo", { bg = "#cca061", fg = "#0ea9c5" })
hi(0, "Hlargs", { link = "@variable.parameter" })
hi(0, "IblIndent", { fg = "#292e42" })
hi(0, "Identifier", { link = "@keyword" })
hi(0, "IlluminatedWordRead", { sp = "#50587f", underline = true })
hi(0, "IlluminatedWordText", { sp = "#50587f", underline = true })
hi(0, "IlluminatedWordWrite", { sp = "#50587f", underline = true })
hi(0, "IncSearch", { bg = "#e8915e", fg = "#16171f" })
hi(0, "Italic", { fg = "#afb9e0", italic = true })
hi(0, "Keyword", { fg = "#73bde9" })
hi(0, "LazyProgressDone", { bold = true, fg = "#e80373" })
hi(0, "LazyProgressTodo", { bold = true, fg = "#383e5b" })
hi(0, "LineNr", { bg = "#181922", fg = "#383e5b" })
hi(0, "LineNrAbove", { bg = "#181922", fg = "#383e5b" })
hi(0, "LineNrBelow", { bg = "#181922", fg = "#383e5b" })
hi(0, "LspCodeLens", { fg = "#50587f" })
hi(0, "LspInfoBorder", { bg = "#16161e", fg = "#2694aa" })
hi(0, "LspInlayHint", { bg = "#1d1f2d", fg = "#4e5675" })
hi(0, "LspKindArray", { link = "@punctuation.bracket" })
hi(0, "LspKindBoolean", { link = "@boolean" })
hi(0, "LspKindClass", { link = "@type" })
hi(0, "LspKindColor", { link = "Special" })
hi(0, "LspKindConstant", { link = "@constant" })
hi(0, "LspKindConstructor", { link = "@constructor" })
hi(0, "LspKindEnum", { link = "@lsp.type.enum" })
hi(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "LspKindEvent", { link = "Special" })
hi(0, "LspKindField", { link = "@variable.member" })
hi(0, "LspKindFile", { link = "Normal" })
hi(0, "LspKindFolder", { link = "Directory" })
hi(0, "LspKindFunction", { link = "@function" })
hi(0, "LspKindInterface", { link = "@lsp.type.interface" })
hi(0, "LspKindKey", { link = "@variable.member" })
hi(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
hi(0, "LspKindMethod", { link = "@function.method" })
hi(0, "LspKindModule", { link = "@module" })
hi(0, "LspKindNamespace", { link = "@module" })
hi(0, "LspKindNull", { link = "@constant.builtin" })
hi(0, "LspKindNumber", { link = "@number" })
hi(0, "LspKindObject", { link = "@constant" })
hi(0, "LspKindOperator", { link = "@operator" })
hi(0, "LspKindPackage", { link = "@module" })
hi(0, "LspKindProperty", { link = "@property" })
hi(0, "LspKindReference", { link = "@markup.link" })
hi(0, "LspKindSnippet", { link = "Conceal" })
hi(0, "LspKindString", { link = "@string" })
hi(0, "LspKindStruct", { link = "@lsp.type.struct" })
hi(0, "LspKindText", { link = "@markup" })
hi(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "LspKindUnit", { link = "@lsp.type.struct" })
hi(0, "LspKindValue", { link = "@string" })
hi(0, "LspKindVariable", { link = "@variable" })
hi(0, "LspReferenceRead", { bg = "#383e5b" })
hi(0, "LspReferenceText", { bg = "#383e5b" })
hi(0, "LspReferenceWrite", { bg = "#383e5b" })
hi(0, "LspSignatureActiveParameter", { bg = "#20253a", bold = true })
hi(0, "MatchParen", { bold = true, fg = "#e8915e" })
hi(0, "ModeMsg", { bold = true, fg = "#9ba2c4" })
hi(0, "MoreMsg", { fg = "#7095e2" })
hi(0, "MsgArea", { fg = "#9ba2c4" })
hi(0, "NonText", { fg = "#4e5675" })
hi(0, "Normal", { bg = "#1a1b26", fg = "#afb9e0" })
hi(0, "NormalFloat", { bg = "#16161e", fg = "#afb9e0" })
hi(0, "NormalNC", { bg = "#1a1b26", fg = "#afb9e0" })
hi(0, "NormalSB", { bg = "#16161e", fg = "#9ba2c4" })
hi(0, "Operator", { fg = "#7ecae9" })
hi(0, "Pmenu", { bg = "#16161e", fg = "#afb9e0" })
hi(0, "PmenuMatch", { bg = "#16161e", fg = "#28b2cc" })
hi(0, "PmenuMatchSel", { bg = "#323750", fg = "#28b2cc" })
hi(0, "PmenuSbar", { bg = "#1f1f29" })
hi(0, "PmenuSel", { bg = "#323750" })
hi(0, "PmenuThumb", { bg = "#383e5b" })
hi(0, "PreProc", { fg = "#6ac7ba" })
hi(0, "Question", { fg = "#7095e2" })
hi(0, "QuickFixLine", { bg = "#283457", bold = true })
hi(0, "Repeat", { link = "Conditional" })
hi(0, "Search", { bg = "#3d59a1", fg = "#afb9e0" })
hi(0, "SignColumn", { bg = "#181922" })
hi(0, "SignColumnSB", { bg = "#16161e", fg = "#383e5b" })
hi(0, "Special", { fg = "#28b2cc" })
hi(0, "SpecialKey", { fg = "#4e5675" })
hi(0, "SpellBad", { sp = "#c84647", undercurl = true })
hi(0, "SpellCap", { sp = "#cca061", undercurl = true })
hi(0, "SpellLocal", { sp = "#0ea9c5", undercurl = true })
hi(0, "SpellRare", { sp = "#1aac90", undercurl = true })
hi(0, "Statement", { fg = "#ab8de2" })
hi(0, "StatusLine", { bg = "#181922" })
hi(0, "StatusLineNC", { bg = "#16161e", fg = "#383e5b" })
hi(0, "Stl0ea9c5_cca061__", { bg = "#cca061", fg = "#0ea9c5" })
hi(0, "Stl181922_0ea9c5__", { bg = "#0ea9c5", fg = "#181922" })
hi(0, "Stl181922_1aac90__", { bg = "#1aac90", fg = "#181922" })
hi(0, "Stl181922_c84647__", { bg = "#c84647", fg = "#181922" })
hi(0, "Stl181922_cca061__", { bg = "#cca061", fg = "#181922" })
hi(0, "Stl1aac90_0ea9c5__", { bg = "#0ea9c5", fg = "#1aac90" })
hi(0, "Stl222534_181922__", { bg = "#181922", fg = "#222534" })
hi(0, "Stl222534_1aac90__", { bg = "#1aac90", fg = "#222534" })
hi(0, "Stl5b638b_222534__", { bg = "#222534", fg = "#5b638b" })
hi(0, "Stl7095e2_222534_bold_", { bg = "#222534", bold = true, fg = "#7095e2" })
hi(0, "Stl_181922__", { bg = "#181922" })
hi(0, "Stl_222534__", { bg = "#222534" })
hi(0, "Stl_222534_bolditalic_", { bg = "#222534", bold = true, italic = true })
hi(0, "Stlc84647_181922__", { bg = "#181922", fg = "#c84647" })
hi(0, "Stlcca061_c84647__", { bg = "#c84647", fg = "#cca061" })
hi(0, "String", { fg = "#1aac90" })
hi(0, "Substitute", { bg = "#e16d84", fg = "#16171f" })
hi(0, "TabLine", { bg = "#16161e", fg = "#383e5b" })
hi(0, "TabLineFill", { bg = "#16171f" })
hi(0, "TabLineSel", { bg = "#7095e2", fg = "#16171f" })
hi(0, "TelescopeBorder", { bg = "#16161e", fg = "#2694aa" })
hi(0, "TelescopeMatching", { bold = true, fg = "#7095e2" })
hi(0, "TelescopeNormal", { bg = "#16161e", fg = "#afb9e0" })
hi(0, "TelescopePreviewTitle", { bg = "#1aac90", fg = "#16161e" })
hi(0, "TelescopePromptBorder", { bg = "#292e42" })
hi(0, "TelescopePromptNormal", { bg = "#292e42" })
hi(0, "TelescopePromptTitle", { bg = "#e80373", fg = "#16161e" })
hi(0, "TelescopeResultsComment", { fg = "#4e5675" })
hi(0, "TelescopeResultsTitle", { fg = "#16161e" })
hi(0, "Title", { bold = true, fg = "#7095e2" })
hi(0, "Todo", { bg = "#cca061", fg = "#1a1b26" })
hi(0, "TreesitterContext", { bg = "#222534" })
hi(0, "Type", { fg = "#3d98a7" })
hi(0, "VertSplit", { fg = "#16171f" })
hi(0, "Visual", { bg = "#283457" })
hi(0, "VisualNOS", { bg = "#283457" })
hi(0, "WarningMsg", { fg = "#cca061" })
hi(0, "WhichKey", { fg = "#73bde9" })
hi(0, "WhichKeyDesc", { fg = "#ab8de2" })
hi(0, "WhichKeyGroup", { fg = "#7095e2" })
hi(0, "WhichKeyNormal", { bg = "#16161e" })
hi(0, "WhichKeySeparator", { fg = "#50587f" })
hi(0, "WhichKeyValue", { fg = "#6a7196" })
hi(0, "Whitespace", { fg = "#383e5b" })
hi(0, "WildMenu", { bg = "#283457" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#16161e" })
hi(0, "debugBreakpoint", { bg = "#192936", fg = "#0ea9c5" })
hi(0, "debugPC", { bg = "#16161e" })
hi(0, "diffAdded", { fg = "#40909e" })
hi(0, "diffChanged", { fg = "#5a79ac" })
hi(0, "diffFile", { fg = "#7095e2" })
hi(0, "diffIndexLine", { fg = "#ab8de2" })
hi(0, "diffLine", { fg = "#50587f" })
hi(0, "diffNewFile", { fg = "#e8915e" })
hi(0, "diffOldFile", { fg = "#cca061" })
hi(0, "diffRemoved", { fg = "#85474f" })
hi(0, "dosIniLabel", { link = "@property" })
hi(0, "healthError", { fg = "#c84647" })
hi(0, "healthSuccess", { fg = "#6ac7ba" })
hi(0, "healthWarning", { fg = "#cca061" })
hi(0, "helpCommand", { bg = "#3d4461", fg = "#7095e2" })
hi(0, "helpExample", { fg = "#50587f" })
hi(0, "htmlH1", { bold = true, fg = "#ab8de2" })
hi(0, "htmlH2", { bold = true, fg = "#7095e2" })
hi(0, "illuminatedCurWord", { bg = "#383e5b" })
hi(0, "illuminatedWord", { bg = "#383e5b" })
hi(0, "lCursor", { bg = "#afb9e0", fg = "#1a1b26" })
hi(0, "qfFileName", { fg = "#7095e2" })
hi(0, "qfLineNr", { fg = "#6a7196" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#24292f"
g.terminal_color_1 = "#b35900"
g.terminal_color_2 = "#0550ae"
g.terminal_color_3 = "#4d2d00"
g.terminal_color_4 = "#0969da"
g.terminal_color_5 = "#8250df"
g.terminal_color_6 = "#1b7c83"
g.terminal_color_7 = "#6e7781"
g.terminal_color_8 = "#57606a"
g.terminal_color_9 = "#8a4600"
g.terminal_color_10 = "#0969da"
g.terminal_color_11 = "#633c01"
g.terminal_color_12 = "#218bff"
g.terminal_color_13 = "#a475f9"
g.terminal_color_14 = "#3192aa"
g.terminal_color_15 = "#8c959f"
