require("plugins.colorscheme")
require("plugins.cmp")
require("plugins.luasnip")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.lualine")
-- require("plugins.feline")
require("plugins.toggleterm")
require("plugins.project")
require("plugins.impatient")
require("plugins.whichkey")
require("plugins.autocommands")

require("plugins.colorizer")
-- require("plugins.vimwiki")
require("plugins.telekasten")
require("plugins.markdown-preview")
require("plugins.dap")
require("plugins.lsp-signature")
-- require("plugins.illuminate")
require("plugins.harpoon")
require("plugins.matchup")
require("plugins.nvim-surround")
require("plugins.dressing")
require("plugins.scrollbar")
require("plugins.neogen")
require("plugins.jupyter-ascending")
-- require("plugins.neogit")
